### PR TITLE
Change the behavior of default iteration to not be infinite

### LINKED ISSUE #5: Infinite loop for Array spread or for-of loop
Hey Sindre,

I just came across this package and noticed that `cycled` object cause infinite loops when being used with Array spread and for-of loops which crashes browsers. Looking at the source code it looks like it's intended.

```
const cycled = new Cycled([1, 2, 3]);

const foo = [...cycled]; // infinite loop
for (let i of cycled) { ... } // infinite loop
```

Unfortunately, I can not wrap my head around at use case for this and I found it rather surprising because you're subclassing Array but this behavior differs from an Array. Can you give me a hint?

Thanks for the great work!

### PR DESCRIPTION
**Pull request by ArfatSalman**
Fixes #5

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -39,7 +39,7 @@ test('.index', t => {
 
 test('.reversed()', t => {
 	const c = new Cycled(fixture);
-	t.is(c.reversed().next().value, 3);
+	t.is(c.indefinitelyReversed().next().value, 3);
```
Comment (sindresorhus) [inline test.js]: Can you add a test for `indefinitely` too?

File: test.js [hunk 2]
```diff
@@ -39,7 +39,7 @@ test('.index', t => {
 
 test('.reversed()', t => {
```
Comment (sindresorhus) [inline test.js]: Title here needs to be updated

File: readme.md [hunk 3]
```diff
@@ -52,7 +52,7 @@ Type: `Array`
 
 ### cycled
 
-The instance is an iterable that will cycle through the array indefinitely.
+The instance is an iterable that will cycle through the array.
```
Comment (sindresorhus) [inline readme.md]: Needs to be more explicit about how it works. It will cycle through the number of elements equaling the length of the array from the current index.

File: index.js [hunk 4]
```diff
@@ -41,7 +49,7 @@ module.exports = class Cycled extends Array {
 		return this.step(-1);
 	}
 
-	get reversed() {
+	get indefinitelyReversed() {
```
Comment (sindresorhus) [inline index.js]: This is a getter, while `indefinitely` is not. Make this one like `indefinitely`.

**Review by sindresorhus — CHANGES_REQUESTED** [review]
